"""25.11 migration

Revision ID: bfbe397fb989
Revises: b963ed4f24a0
Create Date: 2025-11-25 21:46:25.193595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbe397fb989'
down_revision: Union[str, Sequence[str], None] = 'b963ed4f24a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
