from enum import StrEnum


class ErrorCodes(StrEnum):
    # User
    USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST"
    USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS"
    USER_NOT_FOUND_OR_VERIFIED = "USER_NOT_FOUND_OR_VERIFIED"
    DELETE_USER_RANK_LOWER = "DELETE_USER_RANK_LOWER"
    CANNOT_DELETE_ADMIN_USER = "CANNOT_DELETE_ADMIN_USER"
    USER_ALREADY_ADMIN = "USER_ALREADY_ADMIN"
    INVALID_ACTIVATION_PAYLOAD_OR_EXPIRED = "INVALID_ACTIVATION_PAYLOAD_OR_EXPIRED"
    INVALID_RESET_PAYLOAD_OR_EXPIRED = "INVALID_RESET_PAYLOAD_OR_EXPIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT"
    NO_IMAGE_FOUND = "NO_IMAGE_FOUND"

    EXERCISE_NOT_FOUND = "EXERCISE_NOT_FOUND"
    LABORATORY_NOT_FOUND = "LABORATORY_NOT_FOUND"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"

    INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN"

    VISUALIZATION_ERROR = "VISUALIZATION_ERROR"
    DDL_COMMANDS = "DDL_COMMANDS"